### ISSUE TITLE
暗色主题

### ISSUE THREAD

**Issue by sinsong** [amaki-aria/amaki-aria.github.io#8]
我觉得 `黑+白` 稍微有点里亮，于是抄了一下 github 的 Dark dimmed

```scss
$color-text-primary: #adbac7; // 前景
$color-bg-canvas: #22272e; // 背景
$color-text-link: #539bf5; // 链接

body
{
    color: $color-text-primary;
    background-color: $color-bg-canvas;

    // markdown body
    font-family: 'Segoe UI', sans-serif, 'Segoe UI Emoji';
    font-size: 16px;
    line-height: 1.5;
    word-wrap: break-word;
}

p
{
    margin-top: 0;
    margin-bottom: 16px; // 或许太高了
}

a
{
    color: $color-text-link;
    background-color: transparent;
    text-decoration: none;

    &:hover
    {
        text-decoration: underline;
        outline-width: 0;
    }
}
```
